export const subjects: string[] = [
    "slovenščina",
    "matematika",
    "angleščina",
    "madžarščina",
    "italijanščina",
    "likovna umetnost",
    "glasbena umetnost",
    "družba",
    "geografija",
    "zgodovina",
    "domovinska in državljanska kultura in etika",
    "spoznavanje okolja",
    "fizika",
    "kemija",
    "biologija",
    "naravoslovje",
    "naravoslovje in tehnika",
    "tehnika in tehnologija",
    "gospodinjstvo",
    "šport",
    "računalništvo",
    "urejanje besedil",
    "multimedija",
    "računalniška omrežja",
    "umetnost",
    "nemščina",
    "nemščina 1",
    "nemščina 2",
    "nemščina 3",
    "likovno snovanje",
    "likovno snovanje 1",
    "likovno snovanje 2",
    "likovno snovanje 3",
    "španščina",
    "španščina 1",
    "španščina 2",
    "španščina 3",
    "verstva in etika",
    "turistična vzgoja",
    "filozofija",
    "gledališki klub",
    "organizmi v naravi in umetnem okolju",
    "šport za zdravje",
    "sodobna priprava hrane",
    "obdelava gradiv",
    "obdelava gradiv - les",
    "filmska vzgoja",
    "gimnastika",
    "košarka",
    "nogomet",
    "varstvo pred naravnimi in drugimi nesrečami",
    "retorika",
    "šport za sprostitev",
    "načini prehranjevanja",
    "genetika",

    // Gimnazijski predmeti
    "francoščina",
    "ruščina",
    "psihologija",
    "sociologija",
    "informatika"
];
